Unit-tests (#29)
* main branch

* implemented the unit tests for authentication and objects

* fixed the CI and Psalm

* fixed the CI and Psalm show-infor errors

* removed PersonUnitTest

* implemented unit test

* DEBUG

* DEBUG

* enabled the mocking of final classes in PHPUnit

* enabled the mocking of final classes in PHPUnit

* Debug

* Debug

* Removed the getters from resultCounters

* updated the TransactionUnitTest

* fixed integration test for resultcounters

* fixed integration test

* fixed integration test

* updated tests

* seperated all integration tests

* removed all the final keyword

* DEBUG

* resolved changes according to comments

* resolved changes

* invalidbooktest is created

* Added unit test for ResultRow

* chore: remove invalid import

* psalm info issues are fixed

* Added unit test for ResultRow

* Added unit test for ResultRow

* Added final keyword

* fixed broken test and added schema for phpunit.xml

* updated README.md

* Added final keyword to all neccesary classes

* minor errors

* propertynotsetinconstructor is removed

* fixed all warnings

* add coverage options

* explicitly mark test folder in phpunit tests

* remove coverage filter from phpunit xml

* winp

* Deprecations fixed

* Deprecations fixed

* added a new phunitCoverage.xml file for generating a code coverage report

* added a new phunitCoverage.xml file for generating a code coverage report

* removed phunit.cache file and xml-coverage folder

---------

Co-authored-by: Pratiksha <pratiksha@Pratiksha-Nagels>
Co-authored-by: pratikshazalte69 <pratikshazalte69@gmail.com>
Co-authored-by: Kiran Chandani <kiran@nagels.tech>
Co-authored-by: Ghlen Nagels <ghlen@pm.me>

diff --git a/.github/workflows/psalm.yml b/.github/workflows/psalm.yml
--- a/.github/workflows/psalm.yml
+++ b/.github/workflows/psalm.yml
@@ -24,4 +24,15 @@ jobs:
         run: composer install --no-progress --prefer-dist
 
       - name: Run Psalm
-        run: vendor/bin/psalm --output-format=github
+        run: vendor/bin/psalm --show-info=true --output-format=github
+
+      - name: Run Psalm
+        id: psalm
+        run: |
+          # Run Psalm and use tee to print output and save it to psalm.log
+          vendor/bin/psalm --no-cache --show-info=true --output-format=github | tee psalm.log || true
+          # If any warnings are found, print a message and exit with a failure code
+          if grep -q "warning" psalm.log; then
+            echo "Warnings detected in Psalm output. Failing build."
+            exit 1
+          fi
